---
- name: Create a Virtual Machine in Proxmox via API
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Authenticate and Create Session
      uri:
        url: "https://10.1.0.254:8006/api2/json/access/ticket"
        method: POST
        body_format: form-urlencoded
        body:
          username: "test@pam"
          password: "test"
        validate_certs: no
      register: session_response

    - name: Create VM
      uri:
        url: "https://10.1.0.254:8006/api2/json/nodes/pve01/qemu"
        method: POST
        body_format: form-urlencoded
        headers:
          #Content-Type: "application/json"
          CSRFPreventionToken: "{{ session_response.json.data.CSRFPreventionToken }}"
          Cookie: "PVEAuthCookie={{ session_response.json.data.ticket }}"
        body: 
          name: 'dfasdf'
          ide2: 'local:iso/20348.169.210806-2348.fe_release_svc_refresh_SERVER_EVAL_x64FRE_de-de.iso,media=cdrom'
          ostype: l26
          vmid: '{{ vmid }}'
          scsihw: 'virtio-scsi-single'
          scsi0: 'local:32,format=qcow2,iothread=on'
          sockets: 1
          cores: 1
          numa: 0
          cpu: 'x86-64-v2-AES'
          memory: 2048
          net0: 'virtio,bridge=vmbr0,firewall=1'
        validate_certs: no
      register: vm_creation_result

    - debug:
        var: vm_creation_result.json