---
- name: Create a Virtual Machine in Proxmox via API
  hosts: all
  gather_facts: no

  tasks:
    - name: Authenticate and Create Session
      uri:
        url: "https://10.1.0.254:8006/api2/json/access/ticket"
        method: POST
        body_format: json
        body:
          username: "test@pam"
          password: "test"
        validate_certs: no
      register: session_response

    - name: Print the result of login
      debug:
        msg: "output: {{ session_response.json.data.ticket }}"

    - name: Create VM
      uri:
        url: "https://10.1.0.254:8006/api2/json/nodes/pve01/qemu"
        method: POST
        body_format: json
        headers:
          Content-Type: "application/json"
          Cookie: "PVEAuthCookie='PVE:test@pam:65DE9966::cLWR+6o20PuxP+z2ldhh6FhOsEf0+I0FsvHtdgACoIARfUa9yUdX9TT9m5lRAbq+6WKAD6LqhM+SHuy76DEcQ6dVWZGey5qwtOONjEH0jZLnxH0sU+ek//HwTdw1ewd6AqoN8KsdDK9kPGJ46PL2q6NMX6iqnG8jdzYrsQ0j+PmdifFPiSXsPKP3qPRidQ1T781d+bfeIX+XKM/vmCC1sJKwqlhFCrv7IVM5Hm3qqkZoBJaj8LKT7cMcbf72tE6+CLIV3jwEhLR2+Ly3lL/IpVMWaD4bRWiAlpTZrDlI3QUDzSUjvZxepkmMrqujz1AlXWC4H3cyxxtFFWcaFVE18Q=='"
        body: 
          vmid: 150
          name: 'dfasdf'
          ide2: 'local:iso/20348.169.210806-2348.fe_release_svc_refresh_SERVER_EVAL_x64FRE_de-de.iso,media=cdrom'
          ostype: l26
          scsihw: 'virtio-scsi-single'
          scsi0: 'local:32,format=qcow2,iothread=on'
          sockets: 1
          cores: 1
          numa: 0
          cpu: 'x86-64-v2-AES'
          memory: 2048
          net0: 'virtio,bridge=vmbr0,firewall=1'
        validate_certs: no
      register: vm_creation_result

    - debug:
        var: vm_creation_result.json