---
- name: VM
  hosts: all
  gather_facts: no

  tasks:
    - name: Create VM
      uri:
        url: "https://10.1.0.254:8006/api2/json/nodes/pve01/qemu"
        method: POST
        user: "test@pam"
        password: "test"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body: 
          vmid: "222"
          name: "test"
          ostype: l26
          memory: 4096
          sockets: 1
          cores: 2
          ide: "hda"
          ide2: "cdrom"
          net0: "virtio,bridge=vmbr1,tag=2"
          onboot: 1
          boot: c
          disk: "local-lvm:32"
      register: vm_creation_result

    - debug:
        var: vm_creation_result.json